<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('cities')->insert(
            array(
                ['cit_name' => 'اردبیل','cit_prv_id' => '1'],
                ['cit_name' => 'پارس‌آباد','cit_prv_id' => '1'],
                ['cit_name' => 'مشگین شهر','cit_prv_id' => '1'],
                ['cit_name' => 'خلخال','cit_prv_id' => '1'],
                ['cit_name' => 'گرمی','cit_prv_id' => '1'],
                ['cit_name' => 'نمین','cit_prv_id' => '1'],
                ['cit_name' => 'بیله‌سوار','cit_prv_id' => '1'],
                ['cit_name' => 'کوثر','cit_prv_id' => '1'],
                ['cit_name' => 'نیر','cit_prv_id' => '1'],
                ['cit_name' => 'سرعین','cit_prv_id' => '1'],
                ['cit_name' => 'اصفهان','cit_prv_id' => '2',],
                ['cit_name' => 'کاشان','cit_prv_id' => '2',],
                ['cit_name' => 'خمینی‌شهر','cit_prv_id' => '2',],
                ['cit_name' => 'نجف‌آباد','cit_prv_id' => '2',],
                ['cit_name' => 'لنجان','cit_prv_id' => '2',],
                ['cit_name' => 'فلاورجان','cit_prv_id' => '2',],
                ['cit_name' => 'شاهین‌شهر و میمه','cit_prv_id' => '2',],
                ['cit_name' => 'شهرضا','cit_prv_id' => '2',],
                ['cit_name' => 'مبارکه','cit_prv_id' => '2'],
                ['cit_name' => 'برخوار','cit_prv_id' => '2'],
                ['cit_name' => 'آران و بیدگل','cit_prv_id' => '2'],
                ['cit_name' => 'گلپایگان','cit_prv_id' => '2'],
                ['cit_name' => 'سمیرم','cit_prv_id' => '2'],
                ['cit_name' => 'تیران و کرون','cit_prv_id' => '2'],
                ['cit_name' => 'فریدن','cit_prv_id' => '2'],
                ['cit_name' => 'نطنز','cit_prv_id' => '2'],
                ['cit_name' => 'اردستان','cit_prv_id' => '2'],
                ['cit_name' => 'نائین','cit_prv_id' => '2'],
                ['cit_name' => 'فریدون‌شهر','cit_prv_id' => '2'],
                ['cit_name' => 'دهاقان','cit_prv_id' => '2'],
                ['cit_name' => 'خوانسار','cit_prv_id' => '2'],
                ['cit_name' => 'چادگان','cit_prv_id' => '2'],
                ['cit_name' => 'بوئین و میاندشت','cit_prv_id' => '2'],
                ['cit_name' => 'خور و بیابانک','cit_prv_id' => '2'],
                ['cit_name' => 'کرج','cit_prv_id' => '3'],
                ['cit_name' => 'فردیس','cit_prv_id' => '3'],
                ['cit_name' => 'ساوجبلاغ','cit_prv_id' => '3'],
                ['cit_name' => 'نظرآباد','cit_prv_id' => '3'],
                ['cit_name' => 'اشتهارد','cit_prv_id' => '3'],
                ['cit_name' => 'طالقان', 'cit_prv_id' => '3'],
                ['cit_name' => 'ایلام', 'cit_prv_id' => '4'],
                ['cit_name' => 'دهلران', 'cit_prv_id' => '4'],
                ['cit_name' => 'چرداول','cit_prv_id' => '4'],
                ['cit_name' => 'ایوان','cit_prv_id' => '4'],
                ['cit_name' => 'آبدانان','cit_prv_id' => '4'],
                ['cit_name' => 'دره‌شهر','cit_prv_id' => '4'],

                ['cit_name' => 'مهران','cit_prv_id' => '4'],
                ['cit_name' => 'ملکشاهی', 'cit_prv_id' => '4'],
                ['cit_name' => 'بدره', 'cit_prv_id' => '4'],
                ['cit_name' => 'سیروان', 'cit_prv_id' => '4'],
                ['cit_name' => 'تبریز', 'cit_prv_id' => '5'],
                ['cit_name' => 'مراغه', 'cit_prv_id' => '5'],
                ['cit_name' => 'مرند', 'cit_prv_id' => '5'],
                ['cit_name' => 'میانه', 'cit_prv_id' => '5'],
                ['cit_name' => 'اسکو', 'cit_prv_id' => '5'],
                ['cit_name' => 'اهر', 'cit_prv_id' => '5'],
                ['cit_name' => 'شبستر', 'cit_prv_id' => '5'],
                ['cit_name' => 'بناب', 'cit_prv_id' => '5'],
                ['cit_name' => 'سراب', 'cit_prv_id' => '5'],
                ['cit_name' => 'ملکان', 'cit_prv_id' => '5'],
                ['cit_name' => 'آذرشهر', 'cit_prv_id' => '5'],
                ['cit_name' => 'بستان‌آباد', 'cit_prv_id' => '5'],
                ['cit_name' => 'عجب‌شیر', 'cit_prv_id' => '5'],
                ['cit_name' => 'هریس', 'cit_prv_id' => '5'],
                ['cit_name' => 'جلفا', 'cit_prv_id' => '5'],
                ['cit_name' => 'هشترود', 'cit_prv_id' => '5'],
                ['cit_name' => 'ورزقان', 'cit_prv_id' => '5'],
                ['cit_name' => 'کلیبر', 'cit_prv_id' => '5'],
                ['cit_name' => 'خداآفرین', 'cit_prv_id' => '5'],
                ['cit_name' => 'چاراویماق','cit_prv_id' => '5'],
                ['cit_name' => 'ارومیه','cit_prv_id' => '6'],
                ['cit_name' => 'خوی','cit_prv_id' => '6'],
                ['cit_name' => 'میاندوآب','cit_prv_id' => '6'],
                ['cit_name' => 'بوکان', 'cit_prv_id' => '6'],
                ['cit_name' => 'مهاباد','cit_prv_id' => '6'],
                ['cit_name' => 'سلماس', 'cit_prv_id' => '6'],
                ['cit_name' => 'پیرانشهر', 'cit_prv_id' => '6'],
                ['cit_name' => 'نقده', 'cit_prv_id' => '6'],
                ['cit_name' => 'سردشت', 'cit_prv_id' => '6'],
                ['cit_name' => 'ماکو', 'cit_prv_id' => '6'],
                ['cit_name' => 'شاهین‌دژ', 'cit_prv_id' => '6'],
                ['cit_name' => 'تکاب', 'cit_prv_id' => '6'],
                ['cit_name' => 'اشنویه', 'cit_prv_id' => '6'],
                ['cit_name' => 'شوط', 'cit_prv_id' => '6'],
                ['cit_name' => 'چایپاره', 'cit_prv_id' => '6'],
                ['cit_name' => 'چالدران', 'cit_prv_id' => '6'],
                ['cit_name' => 'پلدشت', 'cit_prv_id' => '6'],
                ['cit_name' => 'بوشهر', 'cit_prv_id' => '7'],
                ['cit_name' => 'دشتستان', 'cit_prv_id' => '7'],
                ['cit_name' => 'کنگان', 'cit_prv_id' => '7'],
                ['cit_name' => 'گناوه', 'cit_prv_id' => '7'],
                ['cit_name' => 'دشتی', 'cit_prv_id' => '7'],
                ['cit_name' => 'تنگستان', 'cit_prv_id' => '7'],
                ['cit_name' => 'عسلویه', 'cit_prv_id' => '7'],
                ['cit_name' => 'جم', 'cit_prv_id' => '7'],
                ['cit_name' => 'دیر', 'cit_prv_id' => '7'],
                ['cit_name' => 'دیلم', 'cit_prv_id' => '7'],
                ['cit_name' => 'تهران', 'cit_prv_id' => '8'],
                ['cit_name' => 'شهریار', 'cit_prv_id' => '8'],
                ['cit_name' => 'اسلامشهر', 'cit_prv_id' => '8'],
                ['cit_name' => 'بهارستان', 'cit_prv_id' => '8'],
                ['cit_name' => 'ملارد', 'cit_prv_id' => '8'],
                ['cit_name' => 'پاکدشت', 'cit_prv_id' => '8'],
                ['cit_name' => 'ری', 'cit_prv_id' => '8'],
                ['cit_name' => 'قدس', 'cit_prv_id' => '8'],
                ['cit_name' => 'رباط‌کریم', 'cit_prv_id' => '8'],
                ['cit_name' => 'ورامین', 'cit_prv_id' => '8'],
                ['cit_name' => 'قرچک', 'cit_prv_id' => '8'],
                ['cit_name' => 'پردیس', 'cit_prv_id' => '8'],
                ['cit_name' => 'دماوند', 'cit_prv_id' => '8'],
                ['cit_name' => 'پیشوا', 'cit_prv_id' => '8'],
                ['cit_name' => 'شمیرانات', 'cit_prv_id' => '8'],
                ['cit_name' => 'فیروزکوه', 'cit_prv_id' => '8'],
                ['cit_name' => 'شهرکرد', 'cit_prv_id' => '9'],
                ['cit_name' => 'لردگان', 'cit_prv_id' => '9'],
                ['cit_name' => 'بروجن', 'cit_prv_id' => '9'],
                ['cit_name' => 'فارسان', 'cit_prv_id' => '9'],
                ['cit_name' => 'کیار', 'cit_prv_id' => '9'],
                ['cit_name' => 'اردل', 'cit_prv_id' => '9'],
                ['cit_name' => 'کوهرنگ', 'cit_prv_id' => '9'],
                ['cit_name' => 'سامان', 'cit_prv_id' => '9'],
                ['cit_name' => 'بن', 'cit_prv_id' => '9'],
                ['cit_name' => 'بیرجند', 'cit_prv_id' => '10'],
                ['cit_name' => 'قائنات', 'cit_prv_id' => '10'],
                ['cit_name' => 'طبس', 'cit_prv_id' => '10'],
                ['cit_name' => 'درمیان', 'cit_prv_id' => '10'],
                ['cit_name' => 'نهبندان', 'cit_prv_id' => '10'],
                ['cit_name' => 'فردوس', 'cit_prv_id' => '10'],
                ['cit_name' => 'سربیشه', 'cit_prv_id' => '10'],
                ['cit_name' => 'زیرکوه', 'cit_prv_id' => '10'],
                ['cit_name' => 'سرایان', 'cit_prv_id' => '10'],
                ['cit_name' => 'خوسف', 'cit_prv_id' => '10'],
                ['cit_name' => 'بشرویه', 'cit_prv_id' => '10'],
                ['cit_name' => 'مشهد', 'cit_prv_id' => '11'],
                ['cit_name' => 'نیشابور', 'cit_prv_id' => '11'],
                ['cit_name' => 'سبزوار', 'cit_prv_id' => '11'],
                ['cit_name' => 'تربت جام', 'cit_prv_id' => '11'],
                ['cit_name' => 'تربت حیدریه', 'cit_prv_id' => '11'],
                ['cit_name' => 'قوچان', 'cit_prv_id' => '11'],
                ['cit_name' => 'کاشمر', 'cit_prv_id' => '11'],
                ['cit_name' => 'چناران', 'cit_prv_id' => '11'],
                ['cit_name' => 'خواف', 'cit_prv_id' => '11'],
                ['cit_name' => 'تایباد', 'cit_prv_id' => '11'],
                ['cit_name' => 'فریمان', 'cit_prv_id' => '11'],
                ['cit_name' => 'سرخس', 'cit_prv_id' => '11'],
                ['cit_name' => 'گناباد', 'cit_prv_id' => '11'],
                ['cit_name' => 'بردسکن', 'cit_prv_id' => '11'],
                ['cit_name' => 'درگز', 'cit_prv_id' => '11'],
                ['cit_name' => 'بینالود', 'cit_prv_id' => '11'],
                ['cit_name' => 'زاوه', 'cit_prv_id' => '11'],
                ['cit_name' => 'رشتخوار', 'cit_prv_id' => '11'],
                ['cit_prv_id' => '11', 'cit_name' => 'باخرز'],
                ['cit_name' => 'جوین', 'cit_prv_id' => '11'],
                ['cit_name' => 'خلیل‌آباد', 'cit_prv_id' => '11'],
                ['cit_name' => 'مه‌ولات', 'cit_prv_id' => '11'],
                ['cit_name' => 'جغتای', 'cit_prv_id' => '11'],
                ['cit_name' => 'فیروزه', 'cit_prv_id' => '11'],
                ['cit_name' => 'خوشاب', 'cit_prv_id' => '11'],
                ['cit_name' => 'کلات', 'cit_prv_id' => '11'],
                ['cit_name' => 'بجستان', 'cit_prv_id' => '11'],
                ['cit_name' => 'داورزن', 'cit_prv_id' => '11'],
                ['cit_name' => 'بجنورد', 'cit_prv_id' => '12'],
                ['cit_name' => 'شیروان', 'cit_prv_id' => '12'],
                ['cit_name' => 'اسفراین', 'cit_prv_id' => '12'],
                ['cit_name' => 'مانه و سملقان', 'cit_prv_id' => '12'],
                ['cit_name' => 'راز و جرگلان', 'cit_prv_id' => '12'],
                ['cit_name' => 'فاروج', 'cit_prv_id' => '12'],
                ['cit_name' => 'جاجرم', 'cit_prv_id' => '12'],
                ['cit_name' => 'گرمه', 'cit_prv_id' => '12'],
                ['cit_name' => 'اهواز', 'cit_prv_id' => '13'],
                ['cit_name' => 'دزفول', 'cit_prv_id' => '13'],
                ['cit_name' => 'آبادان', 'cit_prv_id' => '13'],
                ['cit_name' => 'بندر ماهشهر', 'cit_prv_id' => '13'],
                ['cit_name' => 'شوش', 'cit_prv_id' => '13'],
                ['cit_name' => 'ایذه', 'cit_prv_id' => '13'],
                ['cit_name' => 'شوشتر', 'cit_prv_id' => '13'],
                ['cit_name' => 'بهبهان', 'cit_prv_id' => '13'],
                ['cit_name' => 'اندیمشک', 'cit_prv_id' => '13'],
                ['cit_name' => 'خرمشهر', 'cit_prv_id' => '13'],
                ['cit_name' => 'شادگان', 'cit_prv_id' => '13'],
                ['cit_name' => 'رامهرمز', 'cit_prv_id' => '13'],
                ['cit_name' => 'مسجدسلیمان', 'cit_prv_id' => '13'],
                ['cit_name' => 'دشت آزادگان', 'cit_prv_id' => '13'],
                ['cit_name' => 'کارون', 'cit_prv_id' => '13'],
                ['cit_name' => 'باغ‌ملک', 'cit_prv_id' => '13'],
                ['cit_name' => 'باوی', 'cit_prv_id' => '13'],
                ['cit_name' => 'امیدیه', 'cit_prv_id' => '13'],
                ['cit_name' => 'گتوند', 'cit_prv_id' => '13'],
                ['cit_name' => 'رامشیر', 'cit_prv_id' => '13'],
                ['cit_name' => 'حمیدیه', 'cit_prv_id' => '13'],
                ['cit_name' => 'اندیکا', 'cit_prv_id' => '13'],
                ['cit_name' => 'هویزه', 'cit_prv_id' => '13'],
                ['cit_name' => 'هندیجان', 'cit_prv_id' => '13'],
                ['cit_name' => 'لالی', 'cit_prv_id' => '13'],
                ['cit_name' => 'هفتکل', 'cit_prv_id' => '13'],
                ['cit_name' => 'آغاجاری', 'cit_prv_id' => '13'],
                ['cit_name' => 'زنجان', 'cit_prv_id' => '14'],
                ['cit_name' => 'خدابنده', 'cit_prv_id' => '14'],
                ['cit_name' => 'ابهر', 'cit_prv_id' => '14'],
                ['cit_name' => 'خرمدره', 'cit_prv_id' => '14'],
                ['cit_name' => 'طارم', 'cit_prv_id' => '14'],
                ['cit_name' => 'ماهنشان', 'cit_prv_id' => '14'],
                ['cit_name' => 'ایجرود', 'cit_prv_id' => '14'],
                ['cit_name' => 'سلطانیه', 'cit_prv_id' => '14'],
                ['cit_name' => 'شاهرود', 'cit_prv_id' => '15'],
                ['cit_name' => 'سمنان', 'cit_prv_id' => '15'],
                ['cit_name' => 'دامغان', 'cit_prv_id' => '15'],
                ['cit_name' => 'گرمسار', 'cit_prv_id' => '15'],
                ['cit_name' => 'مهدی‌شهر', 'cit_prv_id' => '15'],
                ['cit_name' => 'میامی', 'cit_prv_id' => '15'],
                ['cit_name' => 'سرخه', 'cit_prv_id' => '15'],
                ['cit_name' => 'آرادان', 'cit_prv_id' => '15'],
                ['cit_name' => 'زاهدان', 'cit_prv_id' => '16'],
                ['cit_name' => 'چابهار', 'cit_prv_id' => '16'],
                ['cit_name' => 'ایرانشهر', 'cit_prv_id' => '16'],
                ['cit_name' => 'سراوان', 'cit_prv_id' => '16'],
                ['cit_name' => 'سرباز', 'cit_prv_id' => '16'],
                ['cit_name' => 'خاش', 'cit_prv_id' => '16'],
                ['cit_name' => 'زابل', 'cit_prv_id' => '16'],
                ['cit_name' => 'نیک شهر', 'cit_prv_id' => '16'],
                ['cit_name' => 'کنارک', 'cit_prv_id' => '16'],
                ['cit_name' => 'سیب و سوران', 'cit_prv_id' => '16'],
                ['cit_name' => 'زهک', 'cit_prv_id' => '16'],
                ['cit_name' => 'مهرستان', 'cit_prv_id' => '16'],
                ['cit_name' => 'دلگان', 'cit_prv_id' => '16'],
                ['cit_name' => 'هیرمند', 'cit_prv_id' => '16'],
                ['cit_name' => 'قصرقند', 'cit_prv_id' => '16'],
                ['cit_name' => 'فنوج', 'cit_prv_id' => '16'],
                ['cit_name' => 'نیمروز', 'cit_prv_id' => '16'],
                ['cit_name' => 'میرجاوه', 'cit_prv_id' => '16'],
                ['cit_name' => 'هامون', 'cit_prv_id' => '16'],
                ['cit_name' => 'شیراز','cit_prv_id' => '17'],
                ['cit_name' => 'مرودشت', 'cit_prv_id' => '17'],
                ['cit_name' => 'کازرون', 'cit_prv_id' => '17'],
                ['cit_name' => 'جهرم', 'cit_prv_id' => '17'],
                ['cit_name' => 'لارستان', 'cit_prv_id' => '17'],
                ['cit_name' => 'فسا', 'cit_prv_id' => '17'],
                ['cit_name' => 'داراب', 'cit_prv_id' => '17'],
                ['cit_name' => 'فیروزآباد', 'cit_prv_id' => '17'],
                ['cit_name' => 'ممسنی', 'cit_prv_id' => '17'],
                ['cit_name' => 'نی ریز', 'cit_prv_id' => '17'],
                ['cit_name' => 'آباده', 'cit_prv_id' => '17'],
                ['cit_name' => 'اقلید', 'cit_prv_id' => '17'],
                ['cit_name' => 'لامرد', 'cit_prv_id' => '17'],
                ['cit_name' => 'سپیدان', 'cit_prv_id' => '17'],
                ['cit_name' => 'کوار', 'cit_prv_id' => '17'],
                ['cit_name' => 'زرین‌دشت', 'cit_prv_id' => '17'],
                ['cit_name' => 'قیر و کارزین', 'cit_prv_id' => '17'],
                ['cit_name' => 'استهبان', 'cit_prv_id' => '17'],
                ['cit_name' => 'مهر', 'cit_prv_id' => '17'],
                ['cit_name' => 'خرامه', 'cit_prv_id' => '17'],
                ['cit_name' => 'گراش', 'cit_prv_id' => '17'],
                ['cit_name' => 'خرم‌بید', 'cit_prv_id' => '17'],
                ['cit_name' => 'بوانات', 'cit_prv_id' => '17'],
                ['cit_name' => 'فراشبند', 'cit_prv_id' => '17'],
                ['cit_name' => 'رستم', 'cit_prv_id' => '17'],
                ['cit_name' => 'ارسنجان', 'cit_prv_id' => '17'],
                ['cit_name' => 'خنج', 'cit_prv_id' => '17'],
                ['cit_name' => 'سروستان', 'cit_prv_id' => '17'],
                ['cit_name' => 'پاسارگاد', 'cit_prv_id' => '17'],
                ['cit_name' => 'قزوین', 'cit_prv_id' => '18'],
                ['cit_name' => 'البرز', 'cit_prv_id' => '18'],
                ['cit_name' => 'تاکستان', 'cit_prv_id' => '18',],
                ['cit_name' => 'بوئین‌زهرا', 'cit_prv_id' => '18'],
                ['cit_name' => 'آبیک', 'cit_prv_id' => '18'],
                ['cit_name' => 'آوج', 'cit_prv_id' => '18'],
                ['cit_name' => 'قم', 'cit_prv_id' => '19'],
                ['cit_name' => 'سنندج', 'cit_prv_id' => '20'],
                ['cit_name' => 'سقز', 'cit_prv_id' => '20'],
                ['cit_name' => 'مریوان', 'cit_prv_id' => '20'],
                ['cit_name' => 'بانه', 'cit_prv_id' => '20'],
                ['cit_name' => 'قروه', 'cit_prv_id' => '20'],
                ['cit_name' => 'کامیاران', 'cit_prv_id' => '20'],
                ['cit_name' => 'بیجار', 'cit_prv_id' => '20'],
                ['cit_name' => 'دیواندره', 'cit_prv_id' => '20'],
                ['cit_name' => 'دهگلان', 'cit_prv_id' => '20'],
                ['cit_name' => 'سروآباد','cit_prv_id' => '20'],
                ['cit_name' => 'کرمان', 'cit_prv_id' => '21'],
                ['cit_name' => 'سیرجان', 'cit_prv_id' => '21'],
                ['cit_name' => 'رفسنجان', 'cit_prv_id' => '21'],
                ['cit_name' => 'جیرفت', 'cit_prv_id' => '21'],
                ['cit_name' => 'بم', 'cit_prv_id' => '21'],
                ['cit_name' => 'زرند', 'cit_prv_id' => '21'],
                ['cit_name' => 'رودبار جنوب', 'cit_prv_id' => '21'],
                ['cit_name' => 'شهربابک', 'cit_prv_id' => '21'],
                ['cit_name' => 'کهنوج', 'cit_prv_id' => '21'],
                ['cit_name' => 'ریگان', 'cit_prv_id' => '21'],
                ['cit_name' => 'بافت', 'cit_prv_id' => '21'],
                ['cit_name' => 'عنبرآباد', 'cit_prv_id' => '21'],
                ['cit_name' => 'بردسیر', 'cit_prv_id' => '21'],
                ['cit_name' => 'قلعه گنج', 'cit_prv_id' => '21'],
                ['cit_name' => 'فهرج', 'cit_prv_id' => '21'],
                ['cit_name' => 'منوجان', 'cit_prv_id' => '21'],
                ['cit_name' => 'نرماشیر', 'cit_prv_id' => '21'],
                ['cit_name' => 'راور', 'cit_prv_id' => '21'],
                ['cit_name' => 'ارزوئیه', 'cit_prv_id' => '21'],
                ['cit_name' => 'انار', 'cit_prv_id' => '21'],
                ['cit_name' => 'رابر', 'cit_prv_id' => '21'],
                ['cit_name' => 'فاریاب', 'cit_prv_id' => '21'],
                ['cit_name' => 'کوهبنان', 'cit_prv_id' => '21'],
                ['cit_name' => 'کرمانشاه', 'cit_prv_id' => '22'],
                ['cit_name' => 'اسلام‌آباد غرب', 'cit_prv_id' => '22'],
                ['cit_name' => 'سرپل ذهاب', 'cit_prv_id' => '22'],
                ['cit_name' => 'سنقر', 'cit_prv_id' => '22'],
                ['cit_name' => 'هرسین', 'cit_prv_id' => '22'],
                ['cit_name' => 'کنگاور', 'cit_prv_id' => '22'],
                ['cit_name' => 'جوانرود', 'cit_prv_id' => '22'],
                ['cit_name' => 'صحنه', 'cit_prv_id' => '22'],
                ['cit_name' => 'پاوه', 'cit_prv_id' => '22'],
                ['cit_name' => 'گیلانغرب', 'cit_prv_id' => '22'],
                ['cit_name' => 'روانسر', 'cit_prv_id' => '22'],
                ['cit_name' => 'دالاهو', 'cit_prv_id' => '22'],
                ['cit_name' => 'ثلاث باباجانی', 'cit_prv_id' => '22'],
                ['cit_name' => 'قصرشیرین', 'cit_prv_id' => '22'],
                ['cit_name' => 'بویراحمد', 'cit_prv_id' => '23'],
                ['cit_name' => 'یاسوج', 'cit_prv_id' => '23'],
                ['cit_name' => 'گچساران', 'cit_prv_id' => '23'],
                ['cit_name' => 'دنا', 'cit_prv_id' => '23'],
                ['cit_name' => 'بهمئی', 'cit_prv_id' => '23'],
                ['cit_name' => 'چرام', 'cit_prv_id' => '23'],
                ['cit_name' => 'لنده', 'cit_prv_id' => '23'],
                ['cit_name' => 'باشت', 'cit_prv_id' => '23'],
                ['cit_name' => 'گرگان', 'cit_prv_id' => '24'],
                ['cit_name' => 'گنبد کاووس', 'cit_prv_id' => '24'],
                ['cit_name' => 'علی‌آباد', 'cit_prv_id' => '24'],
                ['cit_name' => 'آق‌قلا', 'cit_prv_id' => '24'],
                ['cit_name' => 'کلاله', 'cit_prv_id' => '24'],
                ['cit_name' => 'آزادشهر', 'cit_prv_id' => '24'],
                ['cit_name' => 'رامیان', 'cit_prv_id' => '24'],
                ['cit_name' => 'ترکمن', 'cit_prv_id' => '24'],
                ['cit_name' => 'مینودشت', 'cit_prv_id' => '24'],
                ['cit_name' => 'کردکوی', 'cit_prv_id' => '24'],
                ['cit_name' => 'گمیشان', 'cit_prv_id' => '24'],
                ['cit_name' => 'گالیکش', 'cit_prv_id' => '24'],
                ['cit_name' => 'مراوه‌تپه', 'cit_prv_id' => '24'],
                ['cit_name' => 'بندر گز', 'cit_prv_id' => '24'],
                ['cit_name' => 'رشت', 'cit_prv_id' => '25'],
                ['cit_name' => 'طوالش', 'cit_prv_id' => '25'],
                ['cit_name' => 'لاهیجان', 'cit_prv_id' => '25'],
                ['cit_name' => 'رودسر', 'cit_prv_id' => '25'],
                ['cit_name' => 'لنگرود', 'cit_prv_id' => '25'],
                ['cit_name' => 'بندر انزلی', 'cit_prv_id' => '25'],
                ['cit_name' => 'صومعه‌سرا', 'cit_prv_id' => '25'],
                ['cit_name' => 'آستانه اشرفیه', 'cit_prv_id' => '25'],
                ['cit_name' => 'رودبار', 'cit_prv_id' => '25'],
                ['cit_name' => 'فومن', 'cit_prv_id' => '25'],
                ['cit_name' => 'آستارا', 'cit_prv_id' => '25'],
                ['cit_name' => 'رضوانشهر', 'cit_prv_id' => '25'],
                ['cit_name' => 'شفت', 'cit_prv_id' => '25'],
                ['cit_name' => 'ماسال', 'cit_prv_id' => '25'],
                ['cit_name' => 'سیاهکل', 'cit_prv_id' => '25'],
                ['cit_name' => 'املش', 'cit_prv_id' => '25'],
                ['cit_name' => 'خرم‌آباد', 'cit_prv_id' => '26'],
                ['cit_name' => 'بروجرد', 'cit_prv_id' => '26'],
                ['cit_name' => 'دورود', 'cit_prv_id' => '26'],
                ['cit_name' => 'کوهدشت', 'cit_prv_id' => '26'],
                ['cit_name' => 'دلفان', 'cit_prv_id' => '26'],
                ['cit_name' => 'الیگودرز', 'cit_prv_id' => '26'],
                ['cit_name' => 'سلسله', 'cit_prv_id' => '26'],
                ['cit_name' => 'ازنا', 'cit_prv_id' => '26'],
                ['cit_name' => 'پلدختر', 'cit_prv_id' => '26'],
                ['cit_name' => 'دوره', 'cit_prv_id' => '26'],
                ['cit_name' => 'رومشکان', 'cit_prv_id' => '26'],
                ['cit_name' => 'ساری', 'cit_prv_id' => '27'],
                ['cit_name' => 'بابل', 'cit_prv_id' => '27'],
                ['cit_name' => 'آمل', 'cit_prv_id' => '27'],
                ['cit_name' => 'قائم‌شهر', 'cit_prv_id' => '27'],
                ['cit_name' => 'بهشهر', 'cit_prv_id' => '27'],
                ['cit_name' => 'تنکابن', 'cit_prv_id' => '27'],
                ['cit_name' => 'نوشهر', 'cit_prv_id' => '27'],
                ['cit_name' => 'بابلسر', 'cit_prv_id' => '27'],
                ['cit_name' => 'نور', 'cit_prv_id' => '27'],
                ['cit_name' => 'نکا', 'cit_prv_id' => '27'],
                ['cit_name' => 'چالوس', 'cit_prv_id' => '27'],
                ['cit_name' => 'محمودآباد', 'cit_prv_id' => '27'],
                ['cit_name' => 'جویبار', 'cit_prv_id' => '27'],
                ['cit_name' => 'رامسر', 'cit_prv_id' => '27'],
                ['cit_name' => 'فریدونکنار', 'cit_prv_id' => '27'],
                ['cit_name' => 'میاندرود', 'cit_prv_id' => '27'],
                ['cit_name' => 'عباس‌آباد', 'cit_prv_id' => '27'],
                ['cit_name' => 'سوادکوه', 'cit_prv_id' => '27'],
                ['cit_name' => 'گلوگاه', 'cit_prv_id' => '27'],
                ['cit_name' => 'سوادکوه شمالی', 'cit_prv_id' => '27'],
                ['cit_name' => 'کلاردشت', 'cit_prv_id' => '27'],
                ['cit_name' => 'سیمرغ', 'cit_prv_id' => '27'],
                ['cit_name' => 'اراک', 'cit_prv_id' => '28'],
                ['cit_name' => 'ساوه', 'cit_prv_id' => '28'],
                ['cit_name' => 'شازند', 'cit_prv_id' => '28'],
                ['cit_name' => 'خمین', 'cit_prv_id' => '28'],
                ['cit_name' => 'زرندیه', 'cit_prv_id' => '28'],
                ['cit_name' => 'محلات', 'cit_prv_id' => '28'],
                ['cit_name' => 'خنداب', 'cit_prv_id' => '28'],
                ['cit_name' => 'دلیجان', 'cit_prv_id' => '28'],
                ['cit_name' => 'کمیجان', 'cit_prv_id' => '28'],
                ['cit_name' => 'فراهان', 'cit_prv_id' => '28'],
                ['cit_name' => 'تفرش', 'cit_prv_id' => '28'],
                ['cit_name' => 'آشتیان', 'cit_prv_id' => '28'],
                ['cit_name' => 'بندرعباس', 'cit_prv_id' => '29'],
                ['cit_name' => 'میناب', 'cit_prv_id' => '29'],
                ['cit_name' => 'بندر لنگه', 'cit_prv_id' => '29'],
                ['cit_name' => 'قشم', 'cit_prv_id' => '29'],
                ['cit_name' => 'رودان', 'cit_prv_id' => '29'],
                ['cit_name' => 'بستک', 'cit_prv_id' => '29'],
                ['cit_name' => 'حاجی‌آباد', 'cit_prv_id' => '29'],
                ['cit_name' => 'جاسک', 'cit_prv_id' => '29'],
                ['cit_name' => 'خمیر', 'cit_prv_id' => '29'],
                ['cit_name' => 'پارسیان', 'cit_prv_id' => '29'],
                ['cit_name' => 'سیریک', 'cit_prv_id' => '29'],
                ['cit_name' => 'بشاگرد', 'cit_prv_id' => '29'],
                ['cit_name' => 'ابوموسی', 'cit_prv_id' => '29'],
                ['cit_name' => 'همدان', 'cit_prv_id' => '30'],
                ['cit_name' => 'ملایر', 'cit_prv_id' => '30'],
                ['cit_name' => 'نهاوند', 'cit_prv_id' => '30'],
                ['cit_name' => 'کبودرآهنگ', 'cit_prv_id' => '30'],
                ['cit_name' => 'بهار', 'cit_prv_id' => '30'],
                ['cit_name' => 'رزن', 'cit_prv_id' => '30'],
                ['cit_name' => 'تویسرکان', 'cit_prv_id' => '30'],
                ['cit_name' => 'اسدآباد', 'cit_prv_id' => '30'],
                ['cit_name' => 'فامنین', 'cit_prv_id' => '30'],
                ['cit_name' => 'یزد', 'cit_prv_id' => '31'],
                ['cit_name' => 'میبد', 'cit_prv_id' => '31'],
                ['cit_name' => 'اردکان', 'cit_prv_id' => '31'],
                ['cit_name' => 'مهریز', 'cit_prv_id' => '31'],
                ['cit_name' => 'ابرکوه', 'cit_prv_id' => '31'],
                ['cit_name' => 'بافق', 'cit_prv_id' => '31'],
                ['cit_name' => 'تفت', 'cit_prv_id' => '31'],
                ['cit_name' => 'خاتم', 'cit_prv_id' => '31'],
                ['cit_name' => 'اشکذر', 'cit_prv_id' => '31'],
                ['cit_name' => 'بهاباد', 'cit_prv_id' => '31'],
                ['cit_name' => 'بندر امام خمینی', 'cit_prv_id' => '13'],
                ['cit_name' => 'بسطام', 'cit_prv_id' => '15'],
                ['cit_name' => 'خفر', 'cit_prv_id' => '17'],
                ['cit_name' => 'صاحب', 'cit_prv_id' => '20'],
                ['cit_name' => 'شیبکوه', 'cit_prv_id' => '29'],
                ['cit_name' => 'میان راهان', 'cit_prv_id' => '22'],
                ['cit_name' => 'امیرآباد', 'cit_prv_id' => '15'],
                ['cit_name' => 'خزل', 'cit_prv_id' => '30'],
                ['cit_name' => 'دهدشت', 'cit_prv_id' => '23'],
                ['cit_name' => 'ماهیدشت', 'cit_prv_id' => '22'],
                ['cit_name' => 'کرانی', 'cit_prv_id' => '20'],
                ['cit_name' => 'جعفرآباد', 'cit_prv_id' => '1'],
                ['cit_name' => 'گلباف', 'cit_prv_id' => '21'],
                ['cit_name' => 'بلداجی', 'cit_prv_id' => '9'],
                ['cit_name' => 'باغ بهادران', 'cit_prv_id' => '2'],
                ['cit_name' => 'جزیره ی خارک', 'cit_prv_id' => '7'],
                ['cit_name' => 'سندرک', 'cit_prv_id' => '29'],
                ['cit_name' => 'قروه درجزین', 'cit_prv_id' => '30'],
            )
        );
    }
}
